name: Vet and Lint Pull Request
on:
  push

jobs:
    build:
        name: Vet and Lint Pull Request
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Prepare binary folder
            run: |
              mkdir bin/

          - name: Setup Go
            uses: actions/setup-go@v3
            with:
              go-version: '1.18'
            
          - name: Go Vet
            run: 'go vet ./...'